### ISSUE TITLE
Status line is missing

### ISSUE THREAD

**Issue by AuthorShin** [MichalSvatos/pi-hole-lcars-next-gen#2]
Hello
Thanks for the awesome theme, I install it and realize there are issues like:
~~1. Status bar is missing.~~
2. The left menu icons are not in the center of the box (I don't know if it's related to the original theme or pihole itself)
~~3. Colors are different from the screenshot you send~~

Edit: It turns out 1 and 3 was causing because I have DARK Reader on my browser :)

<a href="https://ibb.co/Yy15Mxr"><img src="https://i.ibb.co/CMYjZfr/image.png" alt="image" border="0"></a>

**Comment by AuthorShin** [comment]
The Pi-hole is on Debian 10
Pi-hole v5.9  -  FTL v5.14   -    Web Interface v5.11

**Comment by MichalSvatos** [comment]
Thanks for a feedback. It should be better now ([commit](https://github.com/MichalSvatos/pi-hole-lcars-next-gen/commit/542152db8c16c09b99d637da52662986b3a0cc51))
