### ISSUE TITLE
Gravity Update prompts

### ISSUE THREAD

**Issue by tismofied** [MichalSvatos/pi-hole-lcars-next-gen#3]
Outstanding Theme. Thank you so much for making it. I hope it keeps getting updated and not broken by pihole future updates.
One little thing I noticed though under tools>>>update gravity it shows the info pops ups before hitting update. I included an image to show what I mean
![Web capture_23-3-2023_71740_192 168 10 4](https://user-images.githubusercontent.com/90809124/227188476-edea66a9-2f1d-4a8d-8da4-32d205e72671.jpeg)

**Comment by MichalSvatos** [comment]
![Permission to look smug, sir](https://64.media.tumblr.com/64bb9f128c5856372d0e2b1569f3c273/5c131588a27f05d5-76/s640x960/0110a425acf065de7655f2b59544ca5383040868.gifv)!

Thank you!
True, I see. I'll look into it.

**Comment by MichalSvatos** [comment]
:heavy_check_mark: [Fixed](https://github.com/MichalSvatos/pi-hole-lcars-next-gen/commit/2fcb6ffdd01fad8a1e4c67bee05ebc0b9d06e721#diff-725ec461d4c5b190c1fc217b5aea43226f1745a79a659b8fa6a620457c3e19ce)
